SEARCH-3451: add support for CountMinSketch to increment counter by a given number
criblio/node-streamcount pull request #1
Opened 2023-08-29 18:07 UTC by ruslan-dzhumakaliev

**Description**
Add support for CountMinSketch to increment counter by a given number
**Testing**
If your node version is 16.14.* or higher, you may need to add the following line to be able to run the code/UTs
"overrides": {
    "graceful-fs": "^4.2.11"
  }
ref: https://stackoverflow.com/a/58394828

2023-08-29 19:46 UTC, ollidraese requested changes
let's address the performance aspect first

2023-08-29 19:46 UTC, ollidraese commented on lib/countMinSketch.js
> +    if (incrementBy < 0) {
these additional checks (< 0, ==0) now happen on each increment call, which might reduce performance for the original (simple increment) path. I would propose to either remove the check to create a second, independent function to avoid performance regression for original path.

2023-08-29 21:31 UTC, dcheckoway commented on lib/countMinSketch.js
> +    if (incrementBy < 0) {
+1 and I lean toward just removing the check.

2023-08-29 21:32 UTC, dcheckoway commented
Approving since @ollidraese already requested the changes I agree with.  :-)

2023-08-29 21:32 UTC, dcheckoway approved these changes

2023-08-31 17:26 UTC, ruslan-dzhumakaliev commented on lib/countMinSketch.js
> +    if (incrementBy < 0) {
thanks, updated

2023-09-08 23:33 UTC, merged